import { resolve } from 'path';

export default {
  webpack(config, env, helpers, options) {

    //  TODO: Generate style typings file
    helpers.getLoadersByName(config, 'css-loader')
      .forEach(({ loader }) => {
        loader.loader = 'typings-for-css-modules-loader';
        loader.options = Object.assign(loader.options, {
          camelCase: true,
          banner: "// This file is automatically generated from your CSS. Any edits will be overwritten.",
          namedExport: true,
          silent: true,
        });
      });

    config.resolve.alias['preact-cli-entrypoint'] = resolve(
      process.cwd(),
      'src',
      'index'
    );
  }
}