// This file is automatically generated from your CSS. Any edits will be overwritten.
export const websiteRanksContainer: string;
export const websiteRanksMobileTitle: string;
export const websiteRanksItem: string;
export const websiteRanksList: string;
export const websiteRanksHeader: string;
export const websiteRanksTitle: string;
export const websiteRanksTitleIcon: string;
export const websiteRanksTitleText: string;
export const websiteRanksTitleMobileText: string;
export const websiteRanksTitleInfoIcon: string;
