// This file is automatically generated from your CSS. Any edits will be overwritten.
export const h1: string;
export const h2: string;
export const h3: string;
export const h4: string;
export const h5: string;
export const h6: string;
export const subtitle1: string;
export const subtitle2: string;
export const body1: string;
export const body2: string;
export const gutterBottom: string;
export const primary: string;
export const secondary: string;
export const textPrimary: string;
export const textSecondary: string;
export const error: string;
